# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'attacher.ui'
#
# Created: Sun Nov 22 18:11:24 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(540, 407)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.primarylist = QtGui.QListWidget(self.centralwidget)
        self.primarylist.setObjectName("primarylist")
        self.verticalLayout_2.addWidget(self.primarylist)
        self.spouselabel = QtGui.QLabel(self.centralwidget)
        self.spouselabel.setObjectName("spouselabel")
        self.verticalLayout_2.addWidget(self.spouselabel)
        self.spouselist = QtGui.QListWidget(self.centralwidget)
        self.spouselist.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.spouselist.setObjectName("spouselist")
        self.verticalLayout_2.addWidget(self.spouselist)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalGroupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.verticalGroupBox_5.setObjectName("verticalGroupBox_5")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalGroupBox_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioSpouse = QtGui.QRadioButton(self.verticalGroupBox_5)
        self.radioSpouse.setObjectName("radioSpouse")
        self.verticalLayout_3.addWidget(self.radioSpouse)
        self.radioParents = QtGui.QRadioButton(self.verticalGroupBox_5)
        self.radioParents.setObjectName("radioParents")
        self.verticalLayout_3.addWidget(self.radioParents)
        self.radioChild = QtGui.QRadioButton(self.verticalGroupBox_5)
        self.radioChild.setObjectName("radioChild")
        self.verticalLayout_3.addWidget(self.radioChild)
        self.verticalLayout.addWidget(self.verticalGroupBox_5)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.relationGroup = QtGui.QGroupBox(self.centralwidget)
        self.relationGroup.setObjectName("relationGroup")
        self.relationSet = QtGui.QVBoxLayout(self.relationGroup)
        self.relationSet.setObjectName("relationSet")
        self.radioEngaged = QtGui.QRadioButton(self.relationGroup)
        self.radioEngaged.setObjectName("radioEngaged")
        self.relationSet.addWidget(self.radioEngaged)
        self.radioMarried = QtGui.QRadioButton(self.relationGroup)
        self.radioMarried.setObjectName("radioMarried")
        self.relationSet.addWidget(self.radioMarried)
        self.radioDivorced = QtGui.QRadioButton(self.relationGroup)
        self.radioDivorced.setObjectName("radioDivorced")
        self.relationSet.addWidget(self.radioDivorced)
        self.verticalLayout.addWidget(self.relationGroup)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.secondarylist = QtGui.QListWidget(self.centralwidget)
        self.secondarylist.setObjectName("secondarylist")
        self.verticalLayout_4.addWidget(self.secondarylist)
        self.parentlabel = QtGui.QLabel(self.centralwidget)
        self.parentlabel.setObjectName("parentlabel")
        self.verticalLayout_4.addWidget(self.parentlabel)
        self.secondparentlist = QtGui.QListWidget(self.centralwidget)
        self.secondparentlist.setMaximumSize(QtCore.QSize(16777215, 70))
        self.secondparentlist.setObjectName("secondparentlist")
        self.verticalLayout_4.addWidget(self.secondparentlist)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.buttonBox = QtGui.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_5.addWidget(self.buttonBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 540, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.spouselabel.setText(QtGui.QApplication.translate("MainWindow", "Choose spouse", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Select Attach Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.radioSpouse.setText(QtGui.QApplication.translate("MainWindow", "Spouse", None, QtGui.QApplication.UnicodeUTF8))
        self.radioParents.setText(QtGui.QApplication.translate("MainWindow", "Parents", None, QtGui.QApplication.UnicodeUTF8))
        self.radioChild.setText(QtGui.QApplication.translate("MainWindow", "Child", None, QtGui.QApplication.UnicodeUTF8))
        self.radioEngaged.setText(QtGui.QApplication.translate("MainWindow", "Engagement", None, QtGui.QApplication.UnicodeUTF8))
        self.radioMarried.setText(QtGui.QApplication.translate("MainWindow", "Marriage", None, QtGui.QApplication.UnicodeUTF8))
        self.radioDivorced.setText(QtGui.QApplication.translate("MainWindow", "Divorced", None, QtGui.QApplication.UnicodeUTF8))
        self.parentlabel.setText(QtGui.QApplication.translate("MainWindow", "Choose the second parent", None, QtGui.QApplication.UnicodeUTF8))

