# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spouse.ui'
#
# Created: Wed Nov 11 19:23:10 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(270, 210)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(270, 210))
        MainWindow.setMaximumSize(QtCore.QSize(270, 210))
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.marriedButton = QtGui.QRadioButton(self.centralwidget)
        self.marriedButton.setObjectName("marriedButton")
        self.gridLayout_3.addWidget(self.marriedButton, 2, 2, 1, 1)
        self.engagedButton = QtGui.QRadioButton(self.centralwidget)
        self.engagedButton.setObjectName("engagedButton")
        self.gridLayout_3.addWidget(self.engagedButton, 1, 2, 1, 1)
        self.divorcedButton = QtGui.QRadioButton(self.centralwidget)
        self.divorcedButton.setObjectName("divorcedButton")
        self.gridLayout_3.addWidget(self.divorcedButton, 3, 2, 1, 1)
        self.label_status = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_status.sizePolicy().hasHeightForWidth())
        self.label_status.setSizePolicy(sizePolicy)
        self.label_status.setObjectName("label_status")
        self.gridLayout_3.addWidget(self.label_status, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_sdate = QtGui.QLabel(self.centralwidget)
        self.label_sdate.setObjectName("label_sdate")
        self.gridLayout_2.addWidget(self.label_sdate, 1, 0, 1, 1)
        self.label_mdate = QtGui.QLabel(self.centralwidget)
        self.label_mdate.setObjectName("label_mdate")
        self.gridLayout_2.addWidget(self.label_mdate, 0, 0, 1, 1)
        self.marriageEdit = QtGui.QLineEdit(self.centralwidget)
        self.marriageEdit.setObjectName("marriageEdit")
        self.gridLayout_2.addWidget(self.marriageEdit, 0, 1, 1, 1)
        self.separationEdit = QtGui.QLineEdit(self.centralwidget)
        self.separationEdit.setObjectName("separationEdit")
        self.gridLayout_2.addWidget(self.separationEdit, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Discard|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 270, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Spouse Info", None, QtGui.QApplication.UnicodeUTF8))
        self.marriedButton.setText(QtGui.QApplication.translate("MainWindow", "Married", None, QtGui.QApplication.UnicodeUTF8))
        self.engagedButton.setText(QtGui.QApplication.translate("MainWindow", "Engaged", None, QtGui.QApplication.UnicodeUTF8))
        self.divorcedButton.setText(QtGui.QApplication.translate("MainWindow", "Divorced", None, QtGui.QApplication.UnicodeUTF8))
        self.label_status.setText(QtGui.QApplication.translate("MainWindow", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sdate.setText(QtGui.QApplication.translate("MainWindow", "Date of Separation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_mdate.setText(QtGui.QApplication.translate("MainWindow", "Date of Marriage", None, QtGui.QApplication.UnicodeUTF8))

