# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'worker.ui'
#
# Created: Sat Nov  7 18:36:05 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(727, 518)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_dday = QtGui.QLabel(self.centralwidget)
        self.label_dday.setObjectName("label_dday")
        self.gridLayout.addWidget(self.label_dday, 5, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ddayRadio = QtGui.QRadioButton(self.centralwidget)
        self.ddayRadio.setText("")
        self.ddayRadio.setAutoExclusive(False)
        self.ddayRadio.setObjectName("ddayRadio")
        self.horizontalLayout_2.addWidget(self.ddayRadio)
        self.ddayEdit = QtGui.QLineEdit(self.centralwidget)
        self.ddayEdit.setEnabled(False)
        self.ddayEdit.setObjectName("ddayEdit")
        self.horizontalLayout_2.addWidget(self.ddayEdit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 2, 1, 1)
        self.label_notes = QtGui.QLabel(self.centralwidget)
        self.label_notes.setObjectName("label_notes")
        self.gridLayout.addWidget(self.label_notes, 7, 1, 1, 1)
        self.label_father = QtGui.QLabel(self.centralwidget)
        self.label_father.setObjectName("label_father")
        self.gridLayout.addWidget(self.label_father, 1, 3, 1, 1)
        self.label_marriage = QtGui.QLabel(self.centralwidget)
        self.label_marriage.setObjectName("label_marriage")
        self.gridLayout.addWidget(self.label_marriage, 3, 3, 1, 1)
        self.label_mother = QtGui.QLabel(self.centralwidget)
        self.label_mother.setObjectName("label_mother")
        self.gridLayout.addWidget(self.label_mother, 2, 3, 1, 1)
        self.spouselist = QtGui.QListWidget(self.centralwidget)
        self.spouselist.setObjectName("spouselist")
        self.gridLayout.addWidget(self.spouselist, 3, 4, 3, 1)
        self.label_ID = QtGui.QLabel(self.centralwidget)
        self.label_ID.setObjectName("label_ID")
        self.gridLayout.addWidget(self.label_ID, 0, 1, 1, 1)
        self.label_realname = QtGui.QLabel(self.centralwidget)
        self.label_realname.setObjectName("label_realname")
        self.gridLayout.addWidget(self.label_realname, 2, 1, 1, 1)
        self.label_bday = QtGui.QLabel(self.centralwidget)
        self.label_bday.setObjectName("label_bday")
        self.gridLayout.addWidget(self.label_bday, 3, 1, 1, 1)
        self.keyEdit = QtGui.QLineEdit(self.centralwidget)
        self.keyEdit.setReadOnly(True)
        self.keyEdit.setObjectName("keyEdit")
        self.gridLayout.addWidget(self.keyEdit, 0, 2, 1, 1)
        self.nicknameEdit = QtGui.QLineEdit(self.centralwidget)
        self.nicknameEdit.setObjectName("nicknameEdit")
        self.gridLayout.addWidget(self.nicknameEdit, 1, 2, 1, 1)
        self.label_nickname = QtGui.QLabel(self.centralwidget)
        self.label_nickname.setObjectName("label_nickname")
        self.gridLayout.addWidget(self.label_nickname, 1, 1, 1, 1)
        self.realnameEdit = QtGui.QLineEdit(self.centralwidget)
        self.realnameEdit.setObjectName("realnameEdit")
        self.gridLayout.addWidget(self.realnameEdit, 2, 2, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.maleRadio = QtGui.QRadioButton(self.centralwidget)
        self.maleRadio.setObjectName("maleRadio")
        self.horizontalLayout.addWidget(self.maleRadio)
        self.femaleRadio = QtGui.QRadioButton(self.centralwidget)
        self.femaleRadio.setObjectName("femaleRadio")
        self.horizontalLayout.addWidget(self.femaleRadio)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 2, 1, 1)
        self.label_gender = QtGui.QLabel(self.centralwidget)
        self.label_gender.setObjectName("label_gender")
        self.gridLayout.addWidget(self.label_gender, 4, 1, 1, 1)
        self.bdayEdit = QtGui.QLineEdit(self.centralwidget)
        self.bdayEdit.setObjectName("bdayEdit")
        self.gridLayout.addWidget(self.bdayEdit, 3, 2, 1, 1)
        self.label_primarylist = QtGui.QLabel(self.centralwidget)
        self.label_primarylist.setObjectName("label_primarylist")
        self.gridLayout.addWidget(self.label_primarylist, 0, 0, 1, 1)
        self.impRadio = QtGui.QRadioButton(self.centralwidget)
        self.impRadio.setAutoExclusive(False)
        self.impRadio.setObjectName("impRadio")
        self.gridLayout.addWidget(self.impRadio, 6, 2, 1, 1)
        self.notesEdit = QtGui.QTextEdit(self.centralwidget)
        self.notesEdit.setObjectName("notesEdit")
        self.gridLayout.addWidget(self.notesEdit, 7, 2, 2, 1)
        self.peoplelist = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.peoplelist.sizePolicy().hasHeightForWidth())
        self.peoplelist.setSizePolicy(sizePolicy)
        self.peoplelist.setObjectName("peoplelist")
        self.gridLayout.addWidget(self.peoplelist, 1, 0, 8, 1)
        self.motherButton = QtGui.QPushButton(self.centralwidget)
        self.motherButton.setText("")
        self.motherButton.setObjectName("motherButton")
        self.gridLayout.addWidget(self.motherButton, 2, 4, 1, 1)
        self.fatherButton = QtGui.QPushButton(self.centralwidget)
        self.fatherButton.setText("")
        self.fatherButton.setObjectName("fatherButton")
        self.gridLayout.addWidget(self.fatherButton, 1, 4, 1, 1)
        self.childrenlist = QtGui.QListWidget(self.centralwidget)
        self.childrenlist.setObjectName("childrenlist")
        self.gridLayout.addWidget(self.childrenlist, 7, 4, 2, 1)
        self.label_children = QtGui.QLabel(self.centralwidget)
        self.label_children.setObjectName("label_children")
        self.gridLayout.addWidget(self.label_children, 7, 3, 1, 1)
        self.spouseinfo = QtGui.QLineEdit(self.centralwidget)
        self.spouseinfo.setObjectName("spouseinfo")
        self.gridLayout.addWidget(self.spouseinfo, 6, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 727, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAttach = QtGui.QMenu(self.menubar)
        self.menuAttach.setObjectName("menuAttach")
        self.menuPeople = QtGui.QMenu(self.menubar)
        self.menuPeople.setObjectName("menuPeople")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Family = QtGui.QAction(MainWindow)
        self.actionNew_Family.setObjectName("actionNew_Family")
        self.actionParents = QtGui.QAction(MainWindow)
        self.actionParents.setObjectName("actionParents")
        self.actionSpouse = QtGui.QAction(MainWindow)
        self.actionSpouse.setObjectName("actionSpouse")
        self.actionChildren = QtGui.QAction(MainWindow)
        self.actionChildren.setObjectName("actionChildren")
        self.actionDelete_Person = QtGui.QAction(MainWindow)
        self.actionDelete_Person.setObjectName("actionDelete_Person")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave_Family = QtGui.QAction(MainWindow)
        self.actionSave_Family.setObjectName("actionSave_Family")
        self.actionOpen_Family = QtGui.QAction(MainWindow)
        self.actionOpen_Family.setObjectName("actionOpen_Family")
        self.actionMerge_Person = QtGui.QAction(MainWindow)
        self.actionMerge_Person.setObjectName("actionMerge_Person")
        self.actionUnattach = QtGui.QAction(MainWindow)
        self.actionUnattach.setObjectName("actionUnattach")
        self.actionEdit_Spouse = QtGui.QAction(MainWindow)
        self.actionEdit_Spouse.setObjectName("actionEdit_Spouse")
        self.menuFile.addAction(self.actionNew_Family)
        self.menuFile.addAction(self.actionSave_Family)
        self.menuFile.addAction(self.actionOpen_Family)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuAttach.addAction(self.actionParents)
        self.menuAttach.addAction(self.actionSpouse)
        self.menuAttach.addAction(self.actionChildren)
        self.menuAttach.addSeparator()
        self.menuAttach.addAction(self.actionUnattach)
        self.menuPeople.addAction(self.actionMerge_Person)
        self.menuPeople.addAction(self.actionDelete_Person)
        self.menuPeople.addSeparator()
        self.menuPeople.addAction(self.actionEdit_Spouse)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPeople.menuAction())
        self.menubar.addAction(self.menuAttach.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.ddayRadio, QtCore.SIGNAL("toggled(bool)"), self.ddayEdit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_dday.setText(QtGui.QApplication.translate("MainWindow", "Death:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_notes.setText(QtGui.QApplication.translate("MainWindow", "Notes:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_father.setText(QtGui.QApplication.translate("MainWindow", "Father:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_marriage.setText(QtGui.QApplication.translate("MainWindow", "Marriage:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_mother.setText(QtGui.QApplication.translate("MainWindow", "Mother:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ID.setText(QtGui.QApplication.translate("MainWindow", "ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_realname.setText(QtGui.QApplication.translate("MainWindow", "Real Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_bday.setText(QtGui.QApplication.translate("MainWindow", "Birthday:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_nickname.setText(QtGui.QApplication.translate("MainWindow", "Spoken Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.maleRadio.setText(QtGui.QApplication.translate("MainWindow", "Male", None, QtGui.QApplication.UnicodeUTF8))
        self.femaleRadio.setText(QtGui.QApplication.translate("MainWindow", "Female", None, QtGui.QApplication.UnicodeUTF8))
        self.label_gender.setText(QtGui.QApplication.translate("MainWindow", "Gender:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_primarylist.setText(QtGui.QApplication.translate("MainWindow", "List", None, QtGui.QApplication.UnicodeUTF8))
        self.impRadio.setText(QtGui.QApplication.translate("MainWindow", "Important", None, QtGui.QApplication.UnicodeUTF8))
        self.label_children.setText(QtGui.QApplication.translate("MainWindow", "Children:", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAttach.setTitle(QtGui.QApplication.translate("MainWindow", "Attach", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPeople.setTitle(QtGui.QApplication.translate("MainWindow", "People", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Family.setText(QtGui.QApplication.translate("MainWindow", "New Family", None, QtGui.QApplication.UnicodeUTF8))
        self.actionParents.setText(QtGui.QApplication.translate("MainWindow", "Parents", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpouse.setText(QtGui.QApplication.translate("MainWindow", "Spouse", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChildren.setText(QtGui.QApplication.translate("MainWindow", "Children", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete_Person.setText(QtGui.QApplication.translate("MainWindow", "Delete Person", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Family.setText(QtGui.QApplication.translate("MainWindow", "Save Family", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Family.setText(QtGui.QApplication.translate("MainWindow", "Open Family", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMerge_Person.setText(QtGui.QApplication.translate("MainWindow", "Merge Person", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUnattach.setText(QtGui.QApplication.translate("MainWindow", "Unattach", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdit_Spouse.setText(QtGui.QApplication.translate("MainWindow", "Edit Spouse", None, QtGui.QApplication.UnicodeUTF8))

