# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\worker.ui'
#
# Created: Mon Oct 19 22:45:47 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 452)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ddayRadio = QtGui.QRadioButton(self.centralwidget)
        self.ddayRadio.setText("")
        self.ddayRadio.setAutoExclusive(False)
        self.ddayRadio.setObjectName("ddayRadio")
        self.horizontalLayout_2.addWidget(self.ddayRadio)
        self.ddayEdit = QtGui.QLineEdit(self.centralwidget)
        self.ddayEdit.setEnabled(False)
        self.ddayEdit.setObjectName("ddayEdit")
        self.horizontalLayout_2.addWidget(self.ddayEdit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 3, 1, 1)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 6, 3, 1, 1)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 3, 1, 1)
        self.spouselist = QtGui.QListWidget(self.centralwidget)
        self.spouselist.setObjectName("spouselist")
        self.gridLayout.addWidget(self.spouselist, 3, 4, 3, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        self.keyEdit = QtGui.QLineEdit(self.centralwidget)
        self.keyEdit.setReadOnly(True)
        self.keyEdit.setObjectName("keyEdit")
        self.gridLayout.addWidget(self.keyEdit, 0, 2, 1, 1)
        self.nicknameEdit = QtGui.QLineEdit(self.centralwidget)
        self.nicknameEdit.setObjectName("nicknameEdit")
        self.gridLayout.addWidget(self.nicknameEdit, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.realnameEdit = QtGui.QLineEdit(self.centralwidget)
        self.realnameEdit.setObjectName("realnameEdit")
        self.gridLayout.addWidget(self.realnameEdit, 2, 2, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.maleRadio = QtGui.QRadioButton(self.centralwidget)
        self.maleRadio.setObjectName("maleRadio")
        self.horizontalLayout.addWidget(self.maleRadio)
        self.femaleRadio = QtGui.QRadioButton(self.centralwidget)
        self.femaleRadio.setObjectName("femaleRadio")
        self.horizontalLayout.addWidget(self.femaleRadio)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 1, 1, 1)
        self.bdayEdit = QtGui.QLineEdit(self.centralwidget)
        self.bdayEdit.setObjectName("bdayEdit")
        self.gridLayout.addWidget(self.bdayEdit, 3, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.impRadio = QtGui.QRadioButton(self.centralwidget)
        self.impRadio.setAutoExclusive(False)
        self.impRadio.setObjectName("impRadio")
        self.gridLayout.addWidget(self.impRadio, 6, 2, 1, 1)
        self.notesEdit = QtGui.QTextEdit(self.centralwidget)
        self.notesEdit.setObjectName("notesEdit")
        self.gridLayout.addWidget(self.notesEdit, 7, 2, 2, 1)
        self.childrenlist = QtGui.QListWidget(self.centralwidget)
        self.childrenlist.setObjectName("childrenlist")
        self.gridLayout.addWidget(self.childrenlist, 6, 4, 3, 1)
        self.peoplelist = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.peoplelist.sizePolicy().hasHeightForWidth())
        self.peoplelist.setSizePolicy(sizePolicy)
        self.peoplelist.setObjectName("peoplelist")
        self.gridLayout.addWidget(self.peoplelist, 1, 0, 8, 1)
        self.motherButton = QtGui.QPushButton(self.centralwidget)
        self.motherButton.setText("")
        self.motherButton.setObjectName("motherButton")
        self.gridLayout.addWidget(self.motherButton, 2, 4, 1, 1)
        self.fatherButton = QtGui.QPushButton(self.centralwidget)
        self.fatherButton.setText("")
        self.fatherButton.setObjectName("fatherButton")
        self.gridLayout.addWidget(self.fatherButton, 1, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAttach = QtGui.QMenu(self.menubar)
        self.menuAttach.setObjectName("menuAttach")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Family = QtGui.QAction(MainWindow)
        self.actionNew_Family.setObjectName("actionNew_Family")
        self.actionParents = QtGui.QAction(MainWindow)
        self.actionParents.setObjectName("actionParents")
        self.actionSpouse = QtGui.QAction(MainWindow)
        self.actionSpouse.setObjectName("actionSpouse")
        self.actionChildren = QtGui.QAction(MainWindow)
        self.actionChildren.setObjectName("actionChildren")
        self.actionDelete_Person = QtGui.QAction(MainWindow)
        self.actionDelete_Person.setObjectName("actionDelete_Person")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave_Family = QtGui.QAction(MainWindow)
        self.actionSave_Family.setObjectName("actionSave_Family")
        self.actionOpen_Family = QtGui.QAction(MainWindow)
        self.actionOpen_Family.setObjectName("actionOpen_Family")
        self.actionMerge_Person = QtGui.QAction(MainWindow)
        self.actionMerge_Person.setObjectName("actionMerge_Person")
        self.actionUnattach = QtGui.QAction(MainWindow)
        self.actionUnattach.setObjectName("actionUnattach")
        self.menuFile.addAction(self.actionNew_Family)
        self.menuFile.addAction(self.actionSave_Family)
        self.menuFile.addAction(self.actionOpen_Family)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionMerge_Person)
        self.menuFile.addAction(self.actionDelete_Person)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuAttach.addAction(self.actionParents)
        self.menuAttach.addAction(self.actionSpouse)
        self.menuAttach.addAction(self.actionChildren)
        self.menuAttach.addSeparator()
        self.menuAttach.addAction(self.actionUnattach)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAttach.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.ddayRadio, QtCore.SIGNAL("toggled(bool)"), self.ddayEdit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Death:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Notes:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Father:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Marriage:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Children:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Mother:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Real Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Birthday:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Spoken Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.maleRadio.setText(QtGui.QApplication.translate("MainWindow", "Male", None, QtGui.QApplication.UnicodeUTF8))
        self.femaleRadio.setText(QtGui.QApplication.translate("MainWindow", "Female", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Gender:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "List", None, QtGui.QApplication.UnicodeUTF8))
        self.impRadio.setText(QtGui.QApplication.translate("MainWindow", "Important", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAttach.setTitle(QtGui.QApplication.translate("MainWindow", "Attach", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Family.setText(QtGui.QApplication.translate("MainWindow", "New Family", None, QtGui.QApplication.UnicodeUTF8))
        self.actionParents.setText(QtGui.QApplication.translate("MainWindow", "Parents", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpouse.setText(QtGui.QApplication.translate("MainWindow", "Spouse", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChildren.setText(QtGui.QApplication.translate("MainWindow", "Children", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete_Person.setText(QtGui.QApplication.translate("MainWindow", "Delete Person", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Family.setText(QtGui.QApplication.translate("MainWindow", "Save Family", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Family.setText(QtGui.QApplication.translate("MainWindow", "Open Family", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMerge_Person.setText(QtGui.QApplication.translate("MainWindow", "Merge Person", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUnattach.setText(QtGui.QApplication.translate("MainWindow", "Unattach", None, QtGui.QApplication.UnicodeUTF8))

