# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'worker.ui'
#
# Created: Thu Nov 26 14:23:13 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(923, 556)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.primaryList = QtGui.QListWidget(self.centralwidget)
        self.primaryList.setMaximumSize(QtCore.QSize(16777215, 120))
        self.primaryList.setObjectName("primaryList")
        self.gridLayout.addWidget(self.primaryList, 10, 4, 1, 1)
        self.secondaryList = QtGui.QListWidget(self.centralwidget)
        self.secondaryList.setMaximumSize(QtCore.QSize(16777215, 120))
        self.secondaryList.setObjectName("secondaryList")
        self.gridLayout.addWidget(self.secondaryList, 10, 2, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.newFamilyButton = QtGui.QPushButton(self.centralwidget)
        self.newFamilyButton.setObjectName("newFamilyButton")
        self.horizontalLayout_7.addWidget(self.newFamilyButton)
        self.saveFamilyButton = QtGui.QPushButton(self.centralwidget)
        self.saveFamilyButton.setObjectName("saveFamilyButton")
        self.horizontalLayout_7.addWidget(self.saveFamilyButton)
        self.loadFamilyButton = QtGui.QPushButton(self.centralwidget)
        self.loadFamilyButton.setObjectName("loadFamilyButton")
        self.horizontalLayout_7.addWidget(self.loadFamilyButton)
        self.gridLayout.addLayout(self.horizontalLayout_7, 11, 0, 1, 1)
        self.peopleList = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.peopleList.sizePolicy().hasHeightForWidth())
        self.peopleList.setSizePolicy(sizePolicy)
        self.peopleList.setMinimumSize(QtCore.QSize(180, 0))
        self.peopleList.setObjectName("peopleList")
        self.gridLayout.addWidget(self.peopleList, 1, 0, 9, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.attachSpouseButton = QtGui.QPushButton(self.centralwidget)
        self.attachSpouseButton.setObjectName("attachSpouseButton")
        self.horizontalLayout_3.addWidget(self.attachSpouseButton)
        self.attachParentsButton = QtGui.QPushButton(self.centralwidget)
        self.attachParentsButton.setObjectName("attachParentsButton")
        self.horizontalLayout_3.addWidget(self.attachParentsButton)
        self.attachChildButton = QtGui.QPushButton(self.centralwidget)
        self.attachChildButton.setObjectName("attachChildButton")
        self.horizontalLayout_3.addWidget(self.attachChildButton)
        self.gridLayout.addLayout(self.horizontalLayout_3, 11, 4, 1, 1)
        self.bdayEdit = QtGui.QLineEdit(self.centralwidget)
        self.bdayEdit.setObjectName("bdayEdit")
        self.gridLayout.addWidget(self.bdayEdit, 3, 2, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.moveUpSpouse = QtGui.QToolButton(self.centralwidget)
        self.moveUpSpouse.setMaximumSize(QtCore.QSize(25, 16777215))
        self.moveUpSpouse.setObjectName("moveUpSpouse")
        self.verticalLayout_2.addWidget(self.moveUpSpouse)
        self.moveDnSpouse = QtGui.QToolButton(self.centralwidget)
        self.moveDnSpouse.setMaximumSize(QtCore.QSize(25, 16777215))
        self.moveDnSpouse.setObjectName("moveDnSpouse")
        self.verticalLayout_2.addWidget(self.moveDnSpouse)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout_2, 3, 5, 3, 1)
        self.statusToEdit = QtGui.QLineEdit(self.centralwidget)
        self.statusToEdit.setObjectName("statusToEdit")
        self.gridLayout.addWidget(self.statusToEdit, 7, 4, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.moveUpChild = QtGui.QToolButton(self.centralwidget)
        self.moveUpChild.setMaximumSize(QtCore.QSize(25, 16777215))
        self.moveUpChild.setObjectName("moveUpChild")
        self.verticalLayout.addWidget(self.moveUpChild)
        self.moveDnChild = QtGui.QToolButton(self.centralwidget)
        self.moveDnChild.setMaximumSize(QtCore.QSize(25, 16777215))
        self.moveDnChild.setObjectName("moveDnChild")
        self.verticalLayout.addWidget(self.moveDnChild)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout, 8, 5, 2, 1)
        self.spouseList = QtGui.QListWidget(self.centralwidget)
        self.spouseList.setMaximumSize(QtCore.QSize(16777215, 100))
        self.spouseList.setObjectName("spouseList")
        self.gridLayout.addWidget(self.spouseList, 3, 4, 3, 1)
        self.spouseInfo = QtGui.QLineEdit(self.centralwidget)
        self.spouseInfo.setObjectName("spouseInfo")
        self.gridLayout.addWidget(self.spouseInfo, 6, 4, 1, 1)
        self.childrenList = QtGui.QListWidget(self.centralwidget)
        self.childrenList.setObjectName("childrenList")
        self.gridLayout.addWidget(self.childrenList, 8, 4, 2, 1)
        self.notesEdit = QtGui.QTextEdit(self.centralwidget)
        self.notesEdit.setObjectName("notesEdit")
        self.gridLayout.addWidget(self.notesEdit, 8, 2, 2, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.createSpouseButton = QtGui.QPushButton(self.centralwidget)
        self.createSpouseButton.setObjectName("createSpouseButton")
        self.horizontalLayout_4.addWidget(self.createSpouseButton)
        self.createParentsButton = QtGui.QPushButton(self.centralwidget)
        self.createParentsButton.setObjectName("createParentsButton")
        self.horizontalLayout_4.addWidget(self.createParentsButton)
        self.createChildButton = QtGui.QPushButton(self.centralwidget)
        self.createChildButton.setObjectName("createChildButton")
        self.horizontalLayout_4.addWidget(self.createChildButton)
        self.gridLayout.addLayout(self.horizontalLayout_4, 11, 2, 1, 1)
        self.deletePersonButton = QtGui.QPushButton(self.centralwidget)
        self.deletePersonButton.setObjectName("deletePersonButton")
        self.gridLayout.addWidget(self.deletePersonButton, 12, 2, 1, 1)
        self.nicknameEdit = QtGui.QLineEdit(self.centralwidget)
        self.nicknameEdit.setObjectName("nicknameEdit")
        self.gridLayout.addWidget(self.nicknameEdit, 1, 2, 1, 1)
        self.keyEdit = QtGui.QLineEdit(self.centralwidget)
        self.keyEdit.setReadOnly(True)
        self.keyEdit.setObjectName("keyEdit")
        self.gridLayout.addWidget(self.keyEdit, 0, 2, 1, 1)
        self.realnameEdit = QtGui.QLineEdit(self.centralwidget)
        self.realnameEdit.setObjectName("realnameEdit")
        self.gridLayout.addWidget(self.realnameEdit, 2, 2, 1, 1)
        self.peopleListLabel = QtGui.QLabel(self.centralwidget)
        self.peopleListLabel.setObjectName("peopleListLabel")
        self.gridLayout.addWidget(self.peopleListLabel, 0, 0, 1, 1)
        self.fatherButton = QtGui.QPushButton(self.centralwidget)
        self.fatherButton.setText("")
        self.fatherButton.setObjectName("fatherButton")
        self.gridLayout.addWidget(self.fatherButton, 1, 4, 1, 1)
        self.motherButton = QtGui.QPushButton(self.centralwidget)
        self.motherButton.setText("")
        self.motherButton.setObjectName("motherButton")
        self.gridLayout.addWidget(self.motherButton, 2, 4, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.unattachSpouseButton = QtGui.QPushButton(self.centralwidget)
        self.unattachSpouseButton.setObjectName("unattachSpouseButton")
        self.horizontalLayout_5.addWidget(self.unattachSpouseButton)
        self.unattachParentsButton = QtGui.QPushButton(self.centralwidget)
        self.unattachParentsButton.setObjectName("unattachParentsButton")
        self.horizontalLayout_5.addWidget(self.unattachParentsButton)
        self.unattachChildButton = QtGui.QPushButton(self.centralwidget)
        self.unattachChildButton.setObjectName("unattachChildButton")
        self.horizontalLayout_5.addWidget(self.unattachChildButton)
        self.gridLayout.addLayout(self.horizontalLayout_5, 12, 4, 1, 1)
        self.exitButton = QtGui.QPushButton(self.centralwidget)
        self.exitButton.setObjectName("exitButton")
        self.gridLayout.addWidget(self.exitButton, 12, 0, 1, 1)
        self.saveBox = QtGui.QDialogButtonBox(self.centralwidget)
        self.saveBox.setOrientation(QtCore.Qt.Horizontal)
        self.saveBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Save)
        self.saveBox.setCenterButtons(False)
        self.saveBox.setObjectName("saveBox")
        self.gridLayout.addWidget(self.saveBox, 13, 4, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ddayRadio = QtGui.QRadioButton(self.centralwidget)
        self.ddayRadio.setText("")
        self.ddayRadio.setAutoExclusive(False)
        self.ddayRadio.setObjectName("ddayRadio")
        self.horizontalLayout_2.addWidget(self.ddayRadio)
        self.ddayEdit = QtGui.QLineEdit(self.centralwidget)
        self.ddayEdit.setEnabled(False)
        self.ddayEdit.setObjectName("ddayEdit")
        self.horizontalLayout_2.addWidget(self.ddayEdit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 6, 2, 1, 1)
        self.impRadio = QtGui.QRadioButton(self.centralwidget)
        self.impRadio.setAutoExclusive(False)
        self.impRadio.setObjectName("impRadio")
        self.gridLayout.addWidget(self.impRadio, 7, 2, 1, 1)
        self.bdayLabel = QtGui.QLabel(self.centralwidget)
        self.bdayLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.bdayLabel.setObjectName("bdayLabel")
        self.gridLayout.addWidget(self.bdayLabel, 3, 1, 1, 1)
        self.createLabel = QtGui.QLabel(self.centralwidget)
        self.createLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.createLabel.setObjectName("createLabel")
        self.gridLayout.addWidget(self.createLabel, 11, 1, 1, 1)
        self.notesLabel = QtGui.QLabel(self.centralwidget)
        self.notesLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.notesLabel.setObjectName("notesLabel")
        self.gridLayout.addWidget(self.notesLabel, 8, 1, 1, 1)
        self.statusToLabel = QtGui.QLabel(self.centralwidget)
        self.statusToLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.statusToLabel.setObjectName("statusToLabel")
        self.gridLayout.addWidget(self.statusToLabel, 7, 3, 1, 1)
        self.IDLabel = QtGui.QLabel(self.centralwidget)
        self.IDLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.IDLabel.setObjectName("IDLabel")
        self.gridLayout.addWidget(self.IDLabel, 0, 1, 1, 1)
        self.genderLabel = QtGui.QLabel(self.centralwidget)
        self.genderLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.genderLabel.setObjectName("genderLabel")
        self.gridLayout.addWidget(self.genderLabel, 4, 1, 1, 1)
        self.realnameLabel = QtGui.QLabel(self.centralwidget)
        self.realnameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.realnameLabel.setObjectName("realnameLabel")
        self.gridLayout.addWidget(self.realnameLabel, 2, 1, 1, 1)
        self.statusLabel = QtGui.QLabel(self.centralwidget)
        self.statusLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.statusLabel.setObjectName("statusLabel")
        self.gridLayout.addWidget(self.statusLabel, 5, 1, 1, 1)
        self.ddayLabel = QtGui.QLabel(self.centralwidget)
        self.ddayLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.ddayLabel.setObjectName("ddayLabel")
        self.gridLayout.addWidget(self.ddayLabel, 6, 1, 1, 1)
        self.primaryListLabel = QtGui.QLabel(self.centralwidget)
        self.primaryListLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.primaryListLabel.setObjectName("primaryListLabel")
        self.gridLayout.addWidget(self.primaryListLabel, 10, 3, 1, 1)
        self.secondaryListLabel = QtGui.QLabel(self.centralwidget)
        self.secondaryListLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.secondaryListLabel.setObjectName("secondaryListLabel")
        self.gridLayout.addWidget(self.secondaryListLabel, 10, 1, 1, 1)
        self.attachLabel = QtGui.QLabel(self.centralwidget)
        self.attachLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.attachLabel.setObjectName("attachLabel")
        self.gridLayout.addWidget(self.attachLabel, 11, 3, 1, 1)
        self.anniversaryLabel = QtGui.QLabel(self.centralwidget)
        self.anniversaryLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.anniversaryLabel.setObjectName("anniversaryLabel")
        self.gridLayout.addWidget(self.anniversaryLabel, 6, 3, 1, 1)
        self.nicknameLabel = QtGui.QLabel(self.centralwidget)
        self.nicknameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.nicknameLabel.setObjectName("nicknameLabel")
        self.gridLayout.addWidget(self.nicknameLabel, 1, 1, 1, 1)
        self.unattachLabel = QtGui.QLabel(self.centralwidget)
        self.unattachLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.unattachLabel.setObjectName("unattachLabel")
        self.gridLayout.addWidget(self.unattachLabel, 12, 3, 1, 1)
        self.childrenLabel = QtGui.QLabel(self.centralwidget)
        self.childrenLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.childrenLabel.setObjectName("childrenLabel")
        self.gridLayout.addWidget(self.childrenLabel, 8, 3, 1, 1)
        self.marriageLabel = QtGui.QLabel(self.centralwidget)
        self.marriageLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.marriageLabel.setObjectName("marriageLabel")
        self.gridLayout.addWidget(self.marriageLabel, 3, 3, 1, 1)
        self.motherLabel = QtGui.QLabel(self.centralwidget)
        self.motherLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.motherLabel.setObjectName("motherLabel")
        self.gridLayout.addWidget(self.motherLabel, 2, 3, 1, 1)
        self.fatherLabel = QtGui.QLabel(self.centralwidget)
        self.fatherLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.fatherLabel.setObjectName("fatherLabel")
        self.gridLayout.addWidget(self.fatherLabel, 1, 3, 1, 1)
        self.groupBox_1 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_1.setObjectName("groupBox_1")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_1)
        self.horizontalLayout_6.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.secondStatusRadio = QtGui.QRadioButton(self.groupBox_1)
        self.secondStatusRadio.setObjectName("secondStatusRadio")
        self.horizontalLayout_6.addWidget(self.secondStatusRadio)
        self.firstStatusRadio = QtGui.QRadioButton(self.groupBox_1)
        self.firstStatusRadio.setObjectName("firstStatusRadio")
        self.horizontalLayout_6.addWidget(self.firstStatusRadio)
        self.thirdStatusRadio = QtGui.QRadioButton(self.groupBox_1)
        self.thirdStatusRadio.setObjectName("thirdStatusRadio")
        self.horizontalLayout_6.addWidget(self.thirdStatusRadio)
        self.gridLayout.addWidget(self.groupBox_1, 5, 2, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.maleRadio = QtGui.QRadioButton(self.groupBox)
        self.maleRadio.setObjectName("maleRadio")
        self.horizontalLayout.addWidget(self.maleRadio)
        self.femaleRadio = QtGui.QRadioButton(self.groupBox)
        self.femaleRadio.setObjectName("femaleRadio")
        self.horizontalLayout.addWidget(self.femaleRadio)
        self.gridLayout.addWidget(self.groupBox, 4, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 923, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAttach = QtGui.QMenu(self.menubar)
        self.menuAttach.setObjectName("menuAttach")
        self.menuAttach_2 = QtGui.QMenu(self.menuAttach)
        self.menuAttach_2.setObjectName("menuAttach_2")
        self.menuUnattach = QtGui.QMenu(self.menuAttach)
        self.menuUnattach.setObjectName("menuUnattach")
        self.menuPeople = QtGui.QMenu(self.menubar)
        self.menuPeople.setObjectName("menuPeople")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Family = QtGui.QAction(MainWindow)
        self.actionNew_Family.setObjectName("actionNew_Family")
        self.actionParents = QtGui.QAction(MainWindow)
        self.actionParents.setObjectName("actionParents")
        self.actionSpouse = QtGui.QAction(MainWindow)
        self.actionSpouse.setObjectName("actionSpouse")
        self.actionChildren = QtGui.QAction(MainWindow)
        self.actionChildren.setObjectName("actionChildren")
        self.actionDelete_Person = QtGui.QAction(MainWindow)
        self.actionDelete_Person.setObjectName("actionDelete_Person")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave_Family = QtGui.QAction(MainWindow)
        self.actionSave_Family.setObjectName("actionSave_Family")
        self.actionOpen_Family = QtGui.QAction(MainWindow)
        self.actionOpen_Family.setObjectName("actionOpen_Family")
        self.actionMerge_Person = QtGui.QAction(MainWindow)
        self.actionMerge_Person.setObjectName("actionMerge_Person")
        self.actionEdit_Spouse = QtGui.QAction(MainWindow)
        self.actionEdit_Spouse.setObjectName("actionEdit_Spouse")
        self.actionUnParents = QtGui.QAction(MainWindow)
        self.actionUnParents.setObjectName("actionUnParents")
        self.actionMother = QtGui.QAction(MainWindow)
        self.actionMother.setObjectName("actionMother")
        self.actionUnSpouse = QtGui.QAction(MainWindow)
        self.actionUnSpouse.setObjectName("actionUnSpouse")
        self.actionUnChild = QtGui.QAction(MainWindow)
        self.actionUnChild.setObjectName("actionUnChild")
        self.actionUnAll = QtGui.QAction(MainWindow)
        self.actionUnAll.setObjectName("actionUnAll")
        self.actionAttach = QtGui.QAction(MainWindow)
        self.actionAttach.setObjectName("actionAttach")
        self.menuFile.addAction(self.actionNew_Family)
        self.menuFile.addAction(self.actionSave_Family)
        self.menuFile.addAction(self.actionOpen_Family)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuAttach_2.addAction(self.actionParents)
        self.menuAttach_2.addAction(self.actionSpouse)
        self.menuAttach_2.addAction(self.actionChildren)
        self.menuUnattach.addAction(self.actionUnAll)
        self.menuUnattach.addSeparator()
        self.menuUnattach.addAction(self.actionUnParents)
        self.menuUnattach.addAction(self.actionUnSpouse)
        self.menuUnattach.addAction(self.actionUnChild)
        self.menuAttach.addAction(self.menuAttach_2.menuAction())
        self.menuAttach.addSeparator()
        self.menuAttach.addAction(self.actionAttach)
        self.menuAttach.addAction(self.menuUnattach.menuAction())
        self.menuPeople.addAction(self.actionDelete_Person)
        self.menuPeople.addSeparator()
        self.menuPeople.addAction(self.actionEdit_Spouse)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPeople.menuAction())
        self.menubar.addAction(self.menuAttach.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.ddayRadio, QtCore.SIGNAL("toggled(bool)"), self.ddayEdit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.keyEdit, self.nicknameEdit)
        MainWindow.setTabOrder(self.nicknameEdit, self.realnameEdit)
        MainWindow.setTabOrder(self.realnameEdit, self.bdayEdit)
        MainWindow.setTabOrder(self.bdayEdit, self.maleRadio)
        MainWindow.setTabOrder(self.maleRadio, self.femaleRadio)
        MainWindow.setTabOrder(self.femaleRadio, self.ddayRadio)
        MainWindow.setTabOrder(self.ddayRadio, self.ddayEdit)
        MainWindow.setTabOrder(self.ddayEdit, self.impRadio)
        MainWindow.setTabOrder(self.impRadio, self.motherButton)
        MainWindow.setTabOrder(self.motherButton, self.fatherButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.newFamilyButton.setText(QtGui.QApplication.translate("MainWindow", "New Family", None, QtGui.QApplication.UnicodeUTF8))
        self.saveFamilyButton.setText(QtGui.QApplication.translate("MainWindow", "Save Family", None, QtGui.QApplication.UnicodeUTF8))
        self.loadFamilyButton.setText(QtGui.QApplication.translate("MainWindow", "Load Family", None, QtGui.QApplication.UnicodeUTF8))
        self.attachSpouseButton.setText(QtGui.QApplication.translate("MainWindow", "Spouse", None, QtGui.QApplication.UnicodeUTF8))
        self.attachParentsButton.setText(QtGui.QApplication.translate("MainWindow", "Parents", None, QtGui.QApplication.UnicodeUTF8))
        self.attachChildButton.setText(QtGui.QApplication.translate("MainWindow", "Child", None, QtGui.QApplication.UnicodeUTF8))
        self.bdayEdit.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.moveUpSpouse.setText(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.moveDnSpouse.setText(QtGui.QApplication.translate("MainWindow", "Dn", None, QtGui.QApplication.UnicodeUTF8))
        self.moveUpChild.setText(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.moveDnChild.setText(QtGui.QApplication.translate("MainWindow", "Dn", None, QtGui.QApplication.UnicodeUTF8))
        self.createSpouseButton.setText(QtGui.QApplication.translate("MainWindow", "Spouse", None, QtGui.QApplication.UnicodeUTF8))
        self.createParentsButton.setText(QtGui.QApplication.translate("MainWindow", "Parents", None, QtGui.QApplication.UnicodeUTF8))
        self.createChildButton.setText(QtGui.QApplication.translate("MainWindow", "Child", None, QtGui.QApplication.UnicodeUTF8))
        self.deletePersonButton.setText(QtGui.QApplication.translate("MainWindow", "Delete Person", None, QtGui.QApplication.UnicodeUTF8))
        self.peopleListLabel.setText(QtGui.QApplication.translate("MainWindow", "List", None, QtGui.QApplication.UnicodeUTF8))
        self.unattachSpouseButton.setText(QtGui.QApplication.translate("MainWindow", "Spouse", None, QtGui.QApplication.UnicodeUTF8))
        self.unattachParentsButton.setText(QtGui.QApplication.translate("MainWindow", "Parents", None, QtGui.QApplication.UnicodeUTF8))
        self.unattachChildButton.setText(QtGui.QApplication.translate("MainWindow", "Child", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setText(QtGui.QApplication.translate("MainWindow", "Exit Program", None, QtGui.QApplication.UnicodeUTF8))
        self.impRadio.setText(QtGui.QApplication.translate("MainWindow", "Important", None, QtGui.QApplication.UnicodeUTF8))
        self.bdayLabel.setText(QtGui.QApplication.translate("MainWindow", "Birthday:", None, QtGui.QApplication.UnicodeUTF8))
        self.createLabel.setText(QtGui.QApplication.translate("MainWindow", "Create:", None, QtGui.QApplication.UnicodeUTF8))
        self.notesLabel.setText(QtGui.QApplication.translate("MainWindow", "Notes:", None, QtGui.QApplication.UnicodeUTF8))
        self.statusToLabel.setText(QtGui.QApplication.translate("MainWindow", "to:", None, QtGui.QApplication.UnicodeUTF8))
        self.IDLabel.setText(QtGui.QApplication.translate("MainWindow", "ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.genderLabel.setText(QtGui.QApplication.translate("MainWindow", "Gender:", None, QtGui.QApplication.UnicodeUTF8))
        self.realnameLabel.setText(QtGui.QApplication.translate("MainWindow", "Real Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.statusLabel.setText(QtGui.QApplication.translate("MainWindow", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.ddayLabel.setText(QtGui.QApplication.translate("MainWindow", "Death:", None, QtGui.QApplication.UnicodeUTF8))
        self.primaryListLabel.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.secondaryListLabel.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.attachLabel.setText(QtGui.QApplication.translate("MainWindow", "Attach:", None, QtGui.QApplication.UnicodeUTF8))
        self.anniversaryLabel.setText(QtGui.QApplication.translate("MainWindow", "Anniversary:", None, QtGui.QApplication.UnicodeUTF8))
        self.nicknameLabel.setText(QtGui.QApplication.translate("MainWindow", "Spoken Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.unattachLabel.setText(QtGui.QApplication.translate("MainWindow", "Unattach:", None, QtGui.QApplication.UnicodeUTF8))
        self.childrenLabel.setText(QtGui.QApplication.translate("MainWindow", "Children:", None, QtGui.QApplication.UnicodeUTF8))
        self.marriageLabel.setText(QtGui.QApplication.translate("MainWindow", "Marriage:", None, QtGui.QApplication.UnicodeUTF8))
        self.motherLabel.setText(QtGui.QApplication.translate("MainWindow", "Mother:", None, QtGui.QApplication.UnicodeUTF8))
        self.fatherLabel.setText(QtGui.QApplication.translate("MainWindow", "Father:", None, QtGui.QApplication.UnicodeUTF8))
        self.secondStatusRadio.setText(QtGui.QApplication.translate("MainWindow", "Engaged", None, QtGui.QApplication.UnicodeUTF8))
        self.firstStatusRadio.setText(QtGui.QApplication.translate("MainWindow", "Single", None, QtGui.QApplication.UnicodeUTF8))
        self.thirdStatusRadio.setText(QtGui.QApplication.translate("MainWindow", "Divorced", None, QtGui.QApplication.UnicodeUTF8))
        self.maleRadio.setText(QtGui.QApplication.translate("MainWindow", "Male", None, QtGui.QApplication.UnicodeUTF8))
        self.femaleRadio.setText(QtGui.QApplication.translate("MainWindow", "Female", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAttach.setTitle(QtGui.QApplication.translate("MainWindow", "Attach", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAttach_2.setTitle(QtGui.QApplication.translate("MainWindow", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.menuUnattach.setTitle(QtGui.QApplication.translate("MainWindow", "Unattach", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPeople.setTitle(QtGui.QApplication.translate("MainWindow", "People", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Family.setText(QtGui.QApplication.translate("MainWindow", "New Family", None, QtGui.QApplication.UnicodeUTF8))
        self.actionParents.setText(QtGui.QApplication.translate("MainWindow", "Parents", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpouse.setText(QtGui.QApplication.translate("MainWindow", "Spouse", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChildren.setText(QtGui.QApplication.translate("MainWindow", "Child", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete_Person.setText(QtGui.QApplication.translate("MainWindow", "Delete Person", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Family.setText(QtGui.QApplication.translate("MainWindow", "Save Family", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Family.setText(QtGui.QApplication.translate("MainWindow", "Open Family", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMerge_Person.setText(QtGui.QApplication.translate("MainWindow", "Merge Person", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdit_Spouse.setText(QtGui.QApplication.translate("MainWindow", "Edit Spouse", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUnParents.setText(QtGui.QApplication.translate("MainWindow", "Parents", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMother.setText(QtGui.QApplication.translate("MainWindow", "Mother", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUnSpouse.setText(QtGui.QApplication.translate("MainWindow", "Spouse", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUnChild.setText(QtGui.QApplication.translate("MainWindow", "Child", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUnAll.setText(QtGui.QApplication.translate("MainWindow", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAttach.setText(QtGui.QApplication.translate("MainWindow", "Attach", None, QtGui.QApplication.UnicodeUTF8))

